export const ALL_USER_ENDPOINT = '/api/v1/user'
export const ADD_USER_ENDPOINT = '/api/v1/user/addUser'
export const UPDATE_USER_ENDPOINT = '/api/v1/user/updateUser'
export const DELETE_USER_ENDPOINT = '/api/v1/user/removeUser'
export const DELETE_ALL_USER_ENDPOINT = '/api/v1/user/removeAllUsers'
